version: 2

models:
  - name: pipr
    description: "Reading in excel data from ONS"
    config:
        materialized: external
        location: 's3://db.ukre/pipr/data'
        format: csv
        glue_register: true
        glue_database: ukre
