version: 2

models:
  - name: piper_raw
    description: "Reading in excel data from ONS"
    config:
        materialized: external
        location: 's3://db.ukre/piper_raw/data'
        format: csv

  - name: piper_uk
    description: "Basic transfer of data from dbt to athena"
    config:
        materialized: table
