version: 2

models:
  - name: dim_lad
    description: "Loading GEOJSON data from https://geoportal.statistics.gov.uk/datasets/ons::local-authority-districts-may-2024-boundaries-uk-bfc-2/explore"
    config:
        materialized: external
        location: 's3://real-estate-research/dim_lad/output/data'
        format: csv
