version: 2

models:
  - name: hpi
    description: "Reading in excel data from ONS"
    config:
        materialized: external
        location: 's3://db.ukre/hpi/data'
        format: csv
        glue_register: true
        glue_database: ukre