version: 2
sources:
  - name: priceindexofprivaterentsukmonthlypricestatistics
    tables:
      - name: priceindexofprivaterentsukmonthlypricestatistics.xlsx
        config:
          external_location: "read_xlsx(
            'https://www.ons.gov.uk/file?uri=/economy/inflationandpriceindices/datasets/priceindexofprivaterentsukmonthlypricestatistics/18june2025/priceindexofprivaterentsukmonthlypricestatistics.xlsx'
            , range = 'A3:H'
            , sheet='Table 1'
            , ignore_errors=true
            , stop_at_empty = true
            )"

  - name: piper
    database: AwsDataCatalog
    schema: default
    tables:
      - name: raw
        external_location: "s3://ds-dev-bkt/piper/raw"
        meta:
          file_format: csv